type Mutation {
  addUser(
    loginEmail: String!
    password: String!
    firstName: String!
    lastName: String!
    birthDate: Date!
    role: Role
  ): User

  addReservation(
    startDateTime: Date!
    endDateTime: Date!
    userId: ID!
    gymId: ID!
  ): Reservation

  addAddress(
    streetName: String
    buildingNumber: String
    flatNumber: String
    city: String
    zipCode: String
    country: ID
    geoPoint: [Float]
  ): Address

  addGym(
    gymTypeId: ID
    desciption: String
    availability: Int
    equipments: [EquipmentInput!]
  ): Gym

  addGymToSportObject(sportObjectId: ID, gym: GymInput): SportObject

  addGymType(name: String): GymType

  addGymTag(name: String!): GymTag

  addTrainer(
    firstName: String
    lastName: String
    specializations: [SpecializationInput!]
  ): Trainer

  addSportObject(
    name: String
    address: AddressInput
    gyms: [GymInput]
    SportObjectOwnerId: ID
  ): SportObject

  addSportObjectOwner(
    firstName: String
    lastName: String
    companyId: ID
  ): SportObjectOwner

  addCompany(name: String, companyCode: String, address: AddressInput): Company

  addReview(desciption: String, starRate: Float, sportObjectId: ID): Review

  loginUser(loginEmail: String, password: String): String
}
