type Mutation {
  addUser(
    loginEmail: String!
    password: String!
    firstName: String!
    lastName: String!
    birthDate: Date!
    role: Role
  ): User

  addReservation(
    startDateTime: Date!
    endDateTime: Date!
    userId: ID!
    gymId: ID!
  ): Reservation

  addAddress(
    streetName: String
    buildingNumber: String
    flatNumber: String
    city: String
    zipCode: String
    country: ID
    geoPoint: [Float]
  ): Address

  addGym(
    sportObject: String
    gymType: String
    name: String
    description: String
    availability: Int
  ): Gym

  addGymToSportObject(sportObjectId: ID, gym: GymInput): SportObject

  addGymType(name: String, namePL: String): GymType

  addGymTag(name: String! namePL: String): GymTag

  addGymTagToGym(sportObject: String, gym: String, gymTag: String): Gym

  addTrainer(
    firstName: String
    lastName: String
    specializations: [SpecializationInput!]
  ): Trainer

  addSportObject(
    name: String
    address: AddressInput
    gyms: [GymInput]
    SportObjectOwner: String
  ): SportObject

  addSportObjectOwner(
    firstName: String
    lastName: String
    company: String
  ): SportObjectOwner

  addCompany(name: String, companyCode: String, address: AddressInput): Company

  addReview(user: String, description: String, starRate: Float, sportObject: String): Review

  addEquipment(name: String, namePL: String, quantity: Int): Equipment

  addEquipmentToGym(sportObject: String, gym: String, equipment: String): Gym

  loginUser(loginEmail: String, password: String): String

  verifyUser(token: String): JsonToken

  isLoginUserExists(loginEmail: String): Boolean
}
