type Query {
  users: [User]
  userById(userId: String!): User
  userByEmail(loginEmail: String!): User
  reservations: [Reservation]
  userReservations(userId: ID!): [Reservation]
  gyms: [Gym]
  equipments: [Equipment]
  trainers: [Trainer]
  specializations: [Specialization]
  sportObjects: [SportObject]
  addresses: [Address]
  sportObjectOwners: [SportObjectOwner]
  companies: [Company]
  reviews: [Review]
  reviewsByUser(user: String): [Review]
  reviewsByGym(gym: String): [Review]
  cities(filter: String, skip: Int, first: Int): [Cities]
  gymTypes: [GymType]
  gymTags: [GymTag]
  sportObjectByCityAndAvailability(
    city: String
    availability: Int
  ): [SportObject]
  sportObjectByGymType(gymType: String): [SportObject]
}
