type Query {
  users: [User]
  userById(userId: String!): User
  userByEmail(loginEmail: String!): User
  reservations: [Reservation]
  userReservations(user: ID!): [Reservation]
  gyms: [Gym]
  gymById(gymId: ID): Gym
  equipments: [Equipment]
  trainers: [Trainer]
  specializations: [Specialization]
  sportObjects: [SportObject]
  addresses: [Address]
  sportObjectOwners: [SportObjectOwner]
  companies: [Company]
  reviews: [Review]
  reviewsByUser(user: String): [Review]
  reviewsByGym(gym: String): [Review]
  cities(filter: String, skip: Int, first: Int): [Cities]
  gymTypes: [GymType]
  gymTags: [GymTag]
  sportObjectsByCity(city: String): [SportObject]
  sportObjectByGymType(gymType: String): [SportObject]
  sportObjectById(sportObjectId: String): SportObject
}

type SportObject {
  gymById(gymId: ID): Gym
  gymsFilter(
    gymType: ID
    gymTags: [ID]
    minPrice: Float
    maxPrice: Float
    starRate: Float
    availability: Int
    first: Int
    skip: Int
  ): [Gym]
}
