type User {
  _id: ID
  loginEmail: String
  password: String
  firstName: String
  lastName: String
  birthDate: Date
  role: Role
  registeredDate: Date
  reviews: [Review]
}

type Reservation {
  _id: ID
  startDateTime: Date
  endDateTime: Date
  createdAt: Date
  userId: ID
  gymId: ID
}

type Gym {
  _id: ID
  sportObject: SportObject
  gymType: GymType
  name: String
  description: String
  availability: Int
  maxAvailability: Int
  gymTags: [GymTag]
  equipments: [Equipment]
  reviews: [Review]
}

type GymType {
  _id: ID
  name: String
  namePL: String
}

type GymTag {
  _id: ID
  name: String
  namePL: String
}

type Trainer {
  _id: ID
  firstName: String
  lastName: String
  specializations: [Specialization]
}

type Equipment {
  _id: ID
  name: String
  namePL: String
}

type Specialization {
  name: String
  experience: String
}

type SportObject {
  _id: ID
  name: String
  address: Address
  gyms: [Gym]
  sportObjectOwner: SportObjectOwner
}

type SportObjectOwner {
  _id: ID
  firstName: String
  lastName: String
  company: SportObject
}

type Company {
  _id: ID
  name: String
  companyCode: String
  address: Address
}

type Review {
  _id: ID
  user: User
  description: String
  starRate: Float
  sportObject: Gym
}

type Address {
  streetName: String
  buildingNumber: String
  flatNumber: String
  city: String
  zipCode: String
  country: Country
  geoPoint: [Float]
}

type Country {
  code: String
  longName: String
}

type Cities {
  NAZWA: String
  Gmina: String
  Wojewodztwo: String
}

type JsonToken {
  loginEmail: String,
  role: String,
  exp: Int,
  iat: Int
}
